title: True Health
theme: jekyll-theme-minimal
logo: /assets/img/logo.png
show_downloads: [true]
github:
  zip_url: https://github.com/PS-O5/True_Health/releases/download/1.02/True_Health.exe
  tar_url: https://github.com/PS-O5/True_Health/releases/download/1.02/True_Health.exe
